### ISSUE TITLE
是否可以提供下这个项目的Roadmap ?

### ISSUE THREAD

**Issue by node** [Huawei/Huawei_LiteOS_Kernel#1]
特别是未来计划支持的开发板型号列表等部分。

**Comment by PushengHe** [comment]
Huawei_LiteOS_Kernel 这个项目是华为官方支持的，还是一个华为开发爱好者支持的项目？

**Comment by soleverlee** [comment]
@PushengHe 目测是华为官方支持的 去年在osc年度盛会的时候就听到介绍了

**Comment by Issacpeng** [comment]
是华为官方支持的开源项目，当前支持的是STM32 M4核 F411 F429，还在不断扩充，主流的开发板都在支持的计划范围内，支持的开发板的list以及roadmap近期会有一个版本公布出来。 也希望能提出特别想支持的开发板。
