### ISSUE TITLE
is stm32f103 series supported?

### ISSUE THREAD

**Issue by soleverlee** [Huawei/Huawei_LiteOS_Kernel#4]
hoping to support stm32f103* chipsets because it seems that it's more widely used.

**Comment by buruifeng** [comment]
Huawei LiteOS are planning a workshop held in Beijing this Saturday. And we provide a Huawei LiteOS demo that works on stm32f103 board, to demonstrate the whole migrating process.
Here is the workshop portal:
  http://developer.huawei.com/ict/cn/events/site-iot-workshop2016-liteos
For other chipset, wish we can do it together here based the open source project：）

**Comment by soleverlee** [comment]
what an awesome thing!
