### ISSUE TITLE
一系列问题

### ISSUE THREAD

**Issue by tidyjiang8** [Huawei/Huawei_LiteOS_Kernel#5]
- 这个 OS 现在怎么样了？半年不更新，就华为内部玩玩，有意思嘛？
- 为什么支持的开发板如此少，到官网一看，还如此贵？
- 协议栈呢？我咋没看到？
- 我咋感觉这就一普普通通的 mini  "kernel"
- 讲真，**这不叫开源**！

-----------------

伤了很多人的心...

**Comment by Issacpeng** [comment]
Github.com/LiteOS   最新的开发地址，路标正在完善中。

**Comment by tidyjiang8** [comment]
多谢提醒，不过代码里面都还有中文注释，看来你们仅仅面向国内的开发者的。
